### ISSUE TITLE
Inclusion of working example

### ISSUE THREAD

**Issue by shorthouse-mrc** [michaelhall28/darwinian_shift#1]
I'm wondering if the wiki would benefit from a single working example showing how to go from sequencing data, through to checking different classes of mutations for a gene of interest? An example could be NOTCH1, demonstrating how to go from sequencing data to showing significance of high energy mutations, followed by removal of those mutations and the significance of eg. calcium binding residues.

As someone currently trying to reproduce this type of workflow a full use-case would be really useful.

**Comment by michaelhall28** [comment]
Thanks for the suggestion! I've added a working example in the wiki [here](https://github.com/michaelhall28/darwinian_shift/wiki/Example-Analysis)
