### ISSUE TITLE
Amino acid based mutation

### ISSUE THREAD

**Issue by hallba** [michaelhall28/darwinian_shift#3]
Is it possible to work with mutations on an amino acid basis rather than a trinucleotide basis? i.e if you had a list of amino acids that appear at different locations rather than nucleotide substitutions

**Comment by michaelhall28** [comment]
I have made a [new branch](https://github.com/michaelhall28/darwinian_shift/tree/aa_mutations) that allows amino acid changes as the input data. 

There is a brief guide to it [here](https://github.com/michaelhall28/darwinian_shift/wiki/Using-amino-acid-changes-as-input).  

It currently cannot quite do everything that you can with nucleotide-based input - let me know if there is any functionality you need that is not working.
